export class permitFilterData {
    static data=[
    "Verbouwen en/of uitbreiden zonder functiewijziging en met wijzigen van aantal woongelegenheden",
    "Bouwen of herbouwen",
    "Verbouwen en/of uitbreiden van bijgebouwen, niet-overdekte lage constructies of wijzigen van andere beperkte handelingen",
    "Verbouwen en/of uitbreiden zonder functiewijziging en zonder wijziging van aantal woongelegenheden",
    "Verwijderen van vrijstaande gebouwen",
    "Slopen van niet vrijstaande gebouwen of constructies",
    "Nieuwe verkaveling",
    "Hoogstammige bomen vellen die geen deel uitmaken van een bos",
    "Functiewijziging",
    "Nieuwbouw van bijgebouwen, niet-overdekte lage constructies en andere handelingen",
    "Gevel-, dak-, instandhoudings- en renovatiewerken binnen een gebouw, zonder volume- of oppervlaktewijziging",
    "Verbouwen en/of uitbreiden met functiewijziging en met wijziging van het aantal woongelegenheden",
    "Nieuwbouw of aanleggen",
    "Een nieuwe exploitatie",
    "Bijstelling van een verkaveling",
    "Het reliëf van de bodem aanmerkelijk wijzigen",
    "Functiewijziging zonder verbouwingswerken",
    "Bomen vellen die geen deel uitmaken van een bos en/of bodemreliëf wijzigen",
    "Nieuwbouw van bijgebouwen en niet overdekte lage constructie",
    "Verbouwen en/of uitbreiden met functiewijziging en met wijziging van aantal woongelegenheden",
    "Verbouwen / Wijzigen Infrastructuur",
    "Het uitgraven, verbreden, rechttrekken of dichten van kleine landschapselementen",
    "Aanleg van nieuwe verkeersweg",
    "Oprichten van bijgebouwen die aangebouwd zijn aan de woning",
    "Het verwijderen of beschadigen van kleine landschapselementen",
    "Verbouwen en/of uitbreiden met functiewijziging, maar zonder wijziging van het aantal woongelegenheden",
    "Aanleggen van recreatieve terreinen",
    "Het mechanisch of chemisch beschadigen of vernietigen",
    "Verwijderen van vrijstaande bijgebouwen, niet-overdekte lage constructies of andere beperkte handelingen",
    "Een grond gebruiken, aanleggen of inrichten",
    "Verbouwen en/of uitbreiden van bijgebouwen en niet overdekte lage constructies",
    "Wijzigen van een vergund kleinhandelsbedrijf of handelsgeheel",
    "Starten van een ondergeschikte wooneenheid",
    "Ontbossen",
    "Nieuwe publiciteitsinrichting (met inbegrip van vernieuwen van een bestaande vergunning)",
    "Slopen of verwijderen",
    "Nieuwe kleinhandelsactiviteit (netto handelsopp. > 400m²)",
    "Verbouwen en/of uitbreiden zonder functiewijziging en met wijziging van het aantal woongelegenheden",
    "Wijzigen van alle zelfstandige gebruikseenheden (unit) binnen het gebouw",
    "Oprichten van een bijgebouw dat aangebouwd is aan de woning",
    "Wijzigen van een publiciteitsinrichting",
    "Verbouwen en/of uitbreiden met het wijzigen van alle zelfstandige gebruikseenheden (unit) binnen het gebouw",
    "Beëindigen van een ondergeschikte wooneenheid",
    "het rechtstreeks of onrechtstreeks wijzigen van de waterhuishouding",
    "het verwijderen of beschadigen van kleine landschapselemeneten",
    "Slopen of verwijderen van een complex",
    "Het wijzigen van het reliëf",
    "Nieuwbouw of aanleg van een complex",
    "Verbouwen en/of uitbreiden van een complex",
    "Aanpassen van verkeerswegen (tracéwijziging of verbreding)",
    "Wijzigen van recreatieve terreinen",
    "Slopen of verwijderen van een publiciteitsinrichting",
    "Verbouwen zonder functiewijziging en zonder wijziging van aantal woongelegenheden",
    "Het wijzigen van historisch permanente graslanden, inclusief het verbonden microreliëf en poelen",
    "Inrichten van tijdelijke verplaatsbare constructies voor vluchtelingen",
    "Transformation sans changement de fonction et sans changement du nombre d'unités",
    "Transformation d'annexes, de constructions basses non couvertes ou transformation d'autres actions limitées",
    "Travaux à la façade ou au toit, travaux de maintien ou de rénovation dans un bâtiment, sans que la superficie ou le volume ne soit modifié",
    "Verbouwen van bijgebouwen en niet overdekte lage constructies",
    "Verbouwen met functiewijziging en met wijziging van aantal woongelegenheden",
    "Oprichten van een bijgebouw die aangebouwd zijn aan de woning"
    ]

    static category=[
        "All",
        "Bouwen en verbouwen",
        "Bijgebouwen",
        "Nieuwbouw",
        "Afbraakwerken",
        "Grondwerken en verkavelingen",
        "Buitenaanleg",
        "Functiewijziging",
        "Andere"
    ]
    static categoryElements:any={
        "All":null,
        "Bouwen en verbouwen":[
            "Verbouwen en/of uitbreiden zonder functiewijziging en met wijzigen van aantal woongelegenheden",
            "Bouwen of herbouwen",
            "Verbouwen en/of uitbreiden van bijgebouwen, niet-overdekte lage constructies of wijzigen van andere beperkte handelingen",
            "Verbouwen en/of uitbreiden zonder functiewijziging en zonder wijziging van aantal woongelegenheden",
            "Nieuwbouw van bijgebouwen, niet-overdekte lage constructies en andere handelingen",
            "Gevel-, dak-, instandhoudings- en renovatiewerken binnen een gebouw, zonder volume- of oppervlaktewijziging",
            "Verbouwen en/of uitbreiden met functiewijziging en met wijziging van het aantal woongelegenheden",
            "Nieuwbouw van bijgebouwen en niet overdekte lage constructie",
            "Verbouwen en/of uitbreiden met functiewijziging en met wijziging van aantal woongelegenheden",
            "Verbouwen / Wijzigen Infrastructuur",
            "Oprichten van bijgebouwen die aangebouwd zijn aan de woning",
            "Verbouwen en/of uitbreiden met functiewijziging, maar zonder wijziging van het aantal woongelegenheden",
            "Verbouwen en/of uitbreiden van bijgebouwen en niet overdekte lage constructies",
            "Wijzigen van een vergund kleinhandelsbedrijf of handelsgeheel",
            "Starten van een ondergeschikte wooneenheid",
            "Verbouwen en/of uitbreiden zonder functiewijziging en met wijziging van het aantal woongelegenheden",
            "Wijzigen van alle zelfstandige gebruikseenheden (unit) binnen het gebouw",
            "Oprichten van een bijgebouw dat aangebouwd is aan de woning",
            "Verbouwen en/of uitbreiden met het wijzigen van alle zelfstandige gebruikseenheden (unit) binnen het gebouw",
            "Beëindigen van een ondergeschikte wooneenheid",
            "het rechtstreeks of onrechtstreeks wijzigen van de waterhuishouding",
            "Nieuwbouw of aanleg van een complex",
            "Verbouwen en/of uitbreiden van een complex",
            "Verbouwen zonder functiewijziging en zonder wijziging van aantal woongelegenheden",
            "Transformation sans changement de fonction et sans changement du nombre d'unités",
            "Transformation d'annexes, de constructions basses non couvertes ou transformation d'autres actions limitées",
            "Travaux à la façade ou au toit, travaux de maintien ou de rénovation dans un bâtiment, sans que la superficie ou le volume ne soit modifié",
            "Verbouwen van bijgebouwen en niet overdekte lage constructies",
            "Verbouwen met functiewijziging en met wijziging van aantal woongelegenheden",
            "Oprichten van een bijgebouw die aangebouwd zijn aan de woning"        
        ],
        "Bijgebouwen":[
            "Verbouwen en/of uitbreiden van bijgebouwen, niet-overdekte lage constructies of wijzigen van andere beperkte handelingen",
            "Nieuwbouw van bijgebouwen, niet-overdekte lage constructies en andere handelingen",
            "Nieuwbouw van bijgebouwen en niet overdekte lage constructie",
            "Oprichten van bijgebouwen die aangebouwd zijn aan de woning",
            "Verbouwen en/of uitbreiden met functiewijziging, maar zonder wijziging van het aantal woongelegenheden",
            "Verbouwen en/of uitbreiden van bijgebouwen en niet overdekte lage constructies",
            "Oprichten van een bijgebouw dat aangebouwd is aan de woning",
            "Transformation d'annexes, de constructions basses non couvertes ou transformation d'autres actions limitées",
            "Verbouwen van bijgebouwen en niet overdekte lage constructies",
            "Oprichten van een bijgebouw die aangebouwd zijn aan de woning"
        ],
        "Nieuwbouw":[
            "Oprichten van een bijgebouw die aangebouwd zijn aan de woning",
            "Verbouwen en/of uitbreiden van een complex",
            "Nieuwbouw of aanleg van een complex",
            "Oprichten van een bijgebouw dat aangebouwd is aan de woning",
            "Oprichten van bijgebouwen die aangebouwd zijn aan de woning",
            "Nieuwbouw van bijgebouwen en niet overdekte lage constructie",
            "Nieuwbouw of aanleggen",
            "Nieuwbouw van bijgebouwen, niet-overdekte lage constructies en andere handelingen",
            "Nieuwe verkaveling",
            "Bouwen of herbouwen",
        ],
        "Afbraakwerken":[
            "Verwijderen van vrijstaande gebouwen",
            "Het verwijderen of beschadigen van kleine landschapselementen",
            "Het mechanisch of chemisch beschadigen of vernietigen",
            "Verwijderen van vrijstaande bijgebouwen, niet-overdekte lage constructies of andere beperkte handelingen",
            "Slopen of verwijderen",
            "het verwijderen of beschadigen van kleine landschapselemeneten",
            "Slopen of verwijderen van een complex",
            "Slopen of verwijderen van een publiciteitsinrichting",
        ],
        "Grondwerken en verkavelingen":[
            "Nieuwe verkaveling",
            "Bijstelling van een verkaveling",
            "Aanleg van nieuwe verkeersweg",
            "Een grond gebruiken, aanleggen of inrichten",
            "Ontbossen",
            "Aanpassen van verkeerswegen (tracéwijziging of verbreding)",
        ],
        "Buitenaanleg":[
            "Nieuwe verkaveling",
            "Hoogstammige bomen vellen die geen deel uitmaken van een bos",
            "Het reliëf van de bodem aanmerkelijk wijzigen",
            "Bomen vellen die geen deel uitmaken van een bos en/of bodemreliëf wijzigen",
            "Het uitgraven, verbreden, rechttrekken of dichten van kleine landschapselementen",
            "Het verwijderen of beschadigen van kleine landschapselementen",
            "Aanleggen van recreatieve terreinen",
            "Een grond gebruiken, aanleggen of inrichten",
            "Ontbossen",
            "Het wijzigen van het reliëf",
            "Wijzigen van recreatieve terreinen",
            "Het wijzigen van historisch permanente graslanden, inclusief het verbonden microreliëf en poelen",

        ],
        "Functiewijziging":[
            "Verbouwen met functiewijziging en met wijziging van aantal woongelegenheden",
            "Nieuwe kleinhandelsactiviteit (netto handelsopp. > 400m²)",
            "Wijzigen van een vergund kleinhandelsbedrijf of handelsgeheel",
            "Functiewijziging zonder verbouwingswerken",
            "Functiewijziging",

        ],
        "Andere":[
            "Een nieuwe exploitatie",
            "Aanleg van nieuwe verkeersweg",
            "Starten van een ondergeschikte wooneenheid",
            "Nieuwe publiciteitsinrichting (met inbegrip van vernieuwen van een bestaande vergunning)",
            "Wijzigen van een publiciteitsinrichting",
            "Aanpassen van verkeerswegen (tracéwijziging of verbreding)",
            "Inrichten van tijdelijke verplaatsbare constructies voor vluchtelingen",
        ]
    }
    static beslisingStatus=[
        //"Volledig en met voorwaarden toegestaan",
        //"Volledig en zonder voorwaarden toegestaan",
        //"Gedeeltelijk en met voorwaarden toegestaan",
        "Toegestaan",
        "Weigering"
    ]
}
